### ISSUE TITLE
Segmentation fault when sizeof(std::string) <= 2 * sizeof(void*)

### ISSUE THREAD

**Issue by RockinRoel** [thelink2012/any#1]
When using a recent g++ and libstdc++ with -D_GLIBCXX_USE_CXX11_ABI=0, or an older version of g++, sizeof(std::string) is one word. In that case the std::string is placed in stack storage. However, this causes a segmentation fault in some cases.

You can also reproduce this issue with the new ABI and libc++ by increasing the size of stack_storage_t to 4 \* sizeof(void*).

Here's a code sample that reproduces the issue:

```
#include "any.hpp"

#include <iostream>

std::string asString(const linb::any &v)
{
  if (v.type() == typeid(std::string))
    return linb::any_cast<std::string>(v);
  else
    return "";
}

int main()
{
  linb::any a;
  {
    a = std::string("test");
  }
  std::cout << "a: " << asString(a) << std::endl;
}
```

**Comment by thelink2012** [comment]
Interesting. Happens on MSVC as well if I increase stack_storage_t to the sizeof std::string. Also happens with std::vector if stack_storage_t has 4 words.

**Comment by RockinRoel** [comment]
I further narrowed it down to `any_cast<std::string>(const any&)`

```
#include "any.hpp"

#include <iostream>

int main()
{
  linb::any a = std::string("test");
  const linb::any &b = a;
  std::cout << "a: " << linb::any_cast<std::string>(a) << std::endl; // fine
  std::cout << "b: " << linb::any_cast<std::string>(b) << std::endl; // segfault
}
```

**Comment by thelink2012** [comment]
Yeah, `is_nothrow_move_constructible` was returning false for `const T` casts. In this case, `std::string(const std::string&)` throws `bad_alloc`. Now it really checks for `std::string(std::string&&)` :)

Thanks for your report!
