### ISSUE TITLE
Move from rvalue any_cast: opt-out instead opt-in

### ISSUE THREAD

**Issue by trueqbit** [thelink2012/any#12]
Now that we know LWG Defect 2509 has been accepted and C++17 compilers implement it, is there any reason linb::any_cast should continue adhering strictly to the N4562 proposal and keep opting-in to moving rvalues?

I would prefer to have the move-feature enabled by default and opt-out if at all necessary.

**Comment by thelink2012** [comment]
Yeah, makes sense. Fixed by 78b4a8ae4. Thanks!
